app_users/urls.py
from django.urls import path
from . import views
from .views import NewDetailView

# app_name = 'app_users'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('about-school/', views.about_school_view, name='about_school'),
    path('about-us/', views.about_us_view, name='about_us'),
    path('news/', views.news_view, name="news"),
    path('new/<int:pk>/', NewDetailView.as_view(), name='new_detail'),
    path('changepassword/', views.change_password, name='change_password'),
    path('editprofile/', views.edit_profile, name='edit_profile'),
    path('profile/', views.profile, name='profile'),
    path('comments/', views.CommentsListView.as_view(), name='comments'),
]

curriculum/urls.py
from django.urls import path
from . import views

app_name = 'curriculum'
urlpatterns = [
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/', views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(), name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessonDetailView.as_view(), name='lesson_detail'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessonUpdateView.as_view(), name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/', views.LessonDeleteView.as_view(), name='lesson_delete'),
]

teaching_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_users.urls')),
    path('accounts/', include('app_users.urls')),
    path('curriculum/', include('curriculum.urls')),

]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

curriculum/models.py
from django.db import models
from django.db.models.fields.files import ImageField
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.contrib.auth.models import User
import os

from app_users.models import News


# Create your models here.
class Standard(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(null=True, blank=True)
    description = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


def save_subject_image(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.id:
        filename = 'Subject_Pictures/{}.{}'.format(instance.id, ext)
    return os.path.join(upload_to, filename)


class Subject(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE, related_name='subjects')
    image = models.ImageField(upload_to=save_subject_image, blank=True, verbose_name='Subject Image')
    description = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


def save_lesson_files(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.id:
        filename = 'lesson_files/{}/{}.{}'.format(instance.id, instance.id, ext)
        if os.path.exists(filename):
            new_name = str(instance.id) + str('1')
            filename = 'lesson_images/{}/{}.{}'.format(instance.id, new_name, ext)
    return os.path.join(upload_to, filename)


class Lesson(models.Model):
    Standard = models.ForeignKey(Standard, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='lessons')
    name = models.CharField(max_length=250)
    position = models.PositiveSmallIntegerField(verbose_name="Chapter no.")
    slug = models.SlugField(null=True, blank=True)
    video = models.FileField(upload_to=save_lesson_files, verbose_name="Video", blank=True, null=True)
    ppt = models.FileField(upload_to=save_lesson_files, verbose_name="Presentations", blank=True)
    Notes = models.FileField(upload_to=save_lesson_files, verbose_name="Notes", blank=True)

    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('curriculum:lesson_detail', kwargs={'standard': self.Standard.slug, 'subject': self.subject.slug, 'slug': self.name})


class Comment(models.Model):
    lesson_name = models.ForeignKey(Lesson, null=True, blank=True, on_delete=models.CASCADE, related_name='comments_lesson')
    new_name = models.ForeignKey(News, null=True, blank=True, on_delete=models.CASCADE, related_name='comments_new')
    comm_name = models.CharField(max_length=100, blank=True)
    # reply = models.ForeignKey("Comment", null=True, blank=True, on_delete=models.CASCADE,related_name='replies')
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    body = models.TextField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length=100, null=True, blank=True)
    field = models.CharField(max_length=100, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.comm_name = slugify("comment by" + "-" + str(self.author) + str(self.date_added))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.comm_name

    class Meta:
        ordering = ['-date_added']


class Reply(models.Model):
    comment_name = models.ForeignKey(Comment, on_delete=models.CASCADE,related_name='replies')
    reply_body = models.TextField(max_length=500)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length=100, null=True, blank=True)
    field = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return "reply to " + str(self.comment_name.comm_name)


def save_course_image(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.title:
        filename = 'CoursePicture/{}.{}'.format(instance.title, ext)
    return os.path.join(upload_to, filename)


class Courses(models.Model):
    title = models.CharField(max_length=100, blank=True, unique=True)
    description = models.TextField(max_length=500)
    image = models.ImageField(upload_to=save_course_image, blank=True, verbose_name='Course Image')
    
    def __str__(self):
        return self.title

curriculum/forms.py
from django import forms
from .models import Lesson, Reply, Comment


class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ('name', 'position', 'video', 'ppt', 'Notes')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

        labels = {"body": "Comment:"}

        widgets = {
            'body': forms.Textarea(
                attrs={'class': 'form-control', 'rows': 4, 'cols': 70, 'placeholder': "Enter Your Comment"}),
        }


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('reply_body',)

        widgets = {
            'reply_body': forms.Textarea(attrs={'class': 'form-control', 'rows': 2, 'cols': 10}),
        }

curriculum/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.views.generic import (TemplateView, DetailView,
                                  ListView, CreateView,
                                  UpdateView, DeleteView, FormView)
from .models import Standard, Subject, Lesson, Comment
from .forms import LessonForm, ReplyForm, CommentForm
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from app_users.models import UserProfileInfo
from .checkComment.checkComment import checkText
from .checkComment.classificationText import checkNegComment


class StandardListView(ListView):
    context_object_name = 'standards'
    model = Standard
    template_name = 'curriculum/standard_list_view.html'


class SubjectListView(DetailView):
    context_object_name = 'standards'
    model = Standard
    template_name = 'curriculum/subject_list_view.html'


class LessonListView(DetailView):
    context_object_name = 'subjects'
    model = Subject
    template_name = 'curriculum/lesson_list_view.html'


class LessonDetailView(DetailView, FormView):
    context_object_name = 'lessons'
    model = Lesson
    template_name = 'curriculum/lesson_detail_view.html'
    form_class = CommentForm
    second_form_class = ReplyForm

    def get_context_data(self, **kwargs):
        profiles = UserProfileInfo.objects.all()
        users = User.objects.all()
        context = super(LessonDetailView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class()
        context['profiles'] = profiles
        context['users'] = users
        context['comments'] = Comment.objects.filter(lesson_name_id=self.object.id)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'form' in request.POST:
            form_class = self.get_form_class()
            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'

        form = self.get_form(form_class)

        if form.is_valid():
            comment = form.save(commit=False)
            body = comment.body if form_name == 'form' else comment.reply_body
            typeComment = checkText(body.lower())['label']
            comment.type = typeComment
            if typeComment == 'negative':
                field = checkNegComment(body.lower())['label']
                comment.field = field
            # comment.save()

            if form_name == 'form':
                print("comment form is returned")
                return self.form_valid(form)
            elif form_name == 'form2':
                print("reply form is returned")
                return self.form2_valid(form)

        return self.form_invalid(form)

    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.Standard
        subject = self.object.subject
        return reverse_lazy('curriculum:lesson_detail', kwargs={'standard': standard.slug,
                                                                'subject': subject.slug,
                                                                'slug': self.object.slug})

    def form_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.lesson_name = self.object
        fm.lesson_name_id = self.object.id
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

    def form2_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.comment_name_id = self.request.POST.get('comment.id')
        fm.save()
        return HttpResponseRedirect(self.get_success_url())


class LessonCreateView(CreateView):
    # fields = ('lesson_id','name','position','image','video','ppt','Notes')
    form_class = LessonForm
    context_object_name = 'Fanlar'
    model = Subject
    template_name = 'curriculum/lesson_create.html'

    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.standard
        return reverse_lazy('curriculum:lesson_list', kwargs={'standard': standard.slug,
                                                              'slug': self.object.slug})

    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.created_by = self.request.user
        fm.Standard = self.object.standard
        fm.subject = self.object
        fm.save()
        return HttpResponseRedirect(self.get_success_url())


class LessonUpdateView(UpdateView):
    fields = ('name', 'position', 'video', 'ppt', 'Notes')
    model = Lesson
    template_name = 'curriculum/lesson_update.html'
    context_object_name = 'lessons'


class LessonDeleteView(DeleteView):
    model = Lesson
    context_object_name = 'lessons'
    template_name = 'curriculum/lesson_delete.html'

    def get_success_url(self):
        print(self.object)
        standard = self.object.Standard
        subject = self.object.subject
        return reverse_lazy('curriculum:lesson_list', kwargs={'standard': standard.slug, 'slug': subject.slug})

curriculum/templates/curriculum/lesson_create.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Lesson Create {% endblock %}


{% block content %}


{% if user.is_authenticated %}

<div class="site-section ftco-subscribe-1 site-blocks-cover pb-4"
    style="background-image: url('{% static 'images/bg_1.jpg' %}')">
    <div class="container">
        <div class="row align-items-end justify-content-center text-center">
            <div class="col-lg-7">
                <h2 class="mb-0">Yangi dars qo'shish</h2>
                <p>Iltimos ma'lumotlarni aniq qilib yozing</p>
            </div>
        </div>
    </div>
</div>

<div class="custom-breadcrumns border-bottom">
    <div class="container">
        <a href="{% url 'index' %}">Bosh sahifa</a>
        <span class="mx-3 icon-keyboard_arrow_right"></span>
        <a href="{% url 'curriculum:standard_list' %}">Sinflar</a>
        <span class="mx-3 icon-keyboard_arrow_right"></span>
        <span class="current">Yangi dars</span>
    </div>
</div>

<div class="site-section justify-content-center">
    <div class="container ">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <form method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        {% csrf_token %}
                        {{form|crispy}}
                        <input class="btn btn-primary rounded-0 btn-lg btn-block" type="submit" value="Create">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% else %}

<div>
    <h1 style="text-align: center;">Tizimga kirmagansiz!</h1>
</div>

{% endif %}

{% endblock %}

curriculum/templates/curriculum/lesson_delete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Lesson Delete {% endblock %}




{% block content %}

{% if user.is_authenticated %}

<div class="site-section ftco-subscribe-1 site-blocks-cover pb-4"
    style="background-image: url('{% static 'images/bg_1.jpg' %}')">
    <div class="container">
        <div class="row align-items-end justify-content-center text-center">
            <div class="col-lg-7">
                <h2 class="mb-0">Darsni O'chirish</h2>
                <p>Iltimos o'chirayotganingizga ishonch hosil qiling</p>
            </div>
        </div>
    </div>
</div>

<div class="custom-breadcrumns border-bottom">
    <div class="container">
        <a href="{% url 'index' %}">Bosh sahifa</a>
        <span class="mx-3 icon-keyboard_arrow_right"></span>
        <a href="{% url 'curriculum:standard_list' %}">Sinflar</a>
        <span class="mx-3 icon-keyboard_arrow_right"></span>
        <span class="current">Darsni o'chirish</span>
    </div>
</div>

<div class="site-section justify-content-center">
    <div class="container ">
        <div class="row mb-5 justify-content-center text-center">
            <div class="col">
                <h2 class="section-title-underline mb-3">
                    <span>Chindan o'chirasizmi?</span>
                </h2>
                <p>Ma'lumotlarni qayta tiklab bo'lmaydi.</p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-10">
                <form method="post">
                    {% csrf_token %}
                    <div class="row justify-content-center">
                        <div class="col-lg-6" style="margin: 1rem 0;">
                            <input type="submit" value="Ha, o'chirisin"
                                class="btn btn-danger btn-lg mr-4 btn-block rounded-0">
                        </div>
                        <div class="col-md-6" style="margin: 1rem 0;">
                            <a href="{% url 'curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}"
                                class="btn btn-warning btn-lg mr-4 btn-block rounded-0">Bekor qilinsin</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% else %}

<div>
    <h1 style="text-align: center;">Tizimga kirmagansiz!</h1>
</div>

{% endif %}





{% endblock %}

curriculum/templates/curriculum/lesson_list_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{subjects.name}} {% endblock %}


{% block content %}

{% if user.is_authenticated %}

<div class="site-section ftco-subscribe-1 site-blocks-cover pb-4"
    style="background-image: url('{% static 'images/bg_1.jpg' %}')">
    <div class="container">
        <div class="row align-items-end justify-content-center text-center">
            <div class="col-lg-7">
                <h2 class="mb-0">{{subjects.name}}</h2>
                <p>{{subjects.standard}}lar uchun {{subjects.name}} darslari.</p>
            </div>
        </div>
    </div>
</div>

<div class="custom-breadcrumns border-bottom">
    <div class="container">
        <a href="{% url 'index' %}">Bosh sahifa</a>
        <span class="mx-3 icon-keyboard_arrow_right"></span>
        <a href="{% url 'curriculum:standard_list' %}">Sinflar</a>
        <span class="mx-3 icon-keyboard_arrow_right"></span>
        <a href="{% url 'curriculum:subject_list' slug=subjects.standard.slug %}">{{subjects.standard}}</a>
        <span class="mx-3 icon-keyboard_arrow_right"></span>
        <span class="current">{{subjects.name}}</span>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5 justify-content-center text-center">
            <div class="col-lg-4 mb-5">
                <h2 class="section-title-underline mb-5">
                    <span>O'qishni boshlaymiz</span>
                </h2>
            </div>
        </div>
        <div class="row justify-content-center">
            {% if subjects.lessons.all %}
            {% for lesson in subjects.lessons.all %}
            <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                <div class="feature-1 border" style="margin-bottom: 2rem">
                    <div class="icon-wrapper bg-primary">
                        <span class="flaticon-mortarboard text-white"></span>
                    </div>
                    <div class="feature-1-content">
                        <p>{{lesson.position}} - dars</p>
                        <h2>{{lesson.name}}</h2>

                        {% if user.is_authenticated %}
                        <p>
                            <a href="{% url 'curriculum:lesson_detail' slug=lesson.slug subject=subjects.slug standard=lesson.Standard.slug %}"
                                class="btn btn-primary px-4 rounded-0">Darsga o'tish</a>
                        </p>
                        {% else %}
                        <p>
                            <a href="{% url 'user_login' %}" class="btn btn-primary px-4 rounded-0">Darsga o'tish</a>
                        </p>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div style="text-align: center;">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                    class="bi bi-exclamation-triangle" viewBox="0 0 16 16">
                    <path
                        d="M7.938 2.016A.13.13 0 0 1 8.002 2a.13.13 0 0 1 .063.016.146.146 0 0 1 .054.057l6.857 11.667c.036.06.035.124.002.183a.163.163 0 0 1-.054.06.116.116 0 0 1-.066.017H1.146a.115.115 0 0 1-.066-.017.163.163 0 0 1-.054-.06.176.176 0 0 1 .002-.183L7.884 2.073a.147.147 0 0 1 .054-.057zm1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566z" />
                    <path
                        d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995z" />

                </svg>
                <h3> Darslar mavjud emas!</h3>
            </div>
            {% endif %}

        </div>
        <div class="row d-flex justify-content-center mb-3">
            {% if user.userprofileinfo.user_type == 'teacher' or user.is_superuser %}
            <a href="{% url 'curriculum:lesson_create' standard=subjects.standard.slug slug=subjects.slug %}"><button
                    type="button" class="btn btn-info px-4 rounded-0 btn-lg"> Yangi dars qo'shish </button> </a>
            {% endif %}
        </div>
    </div>
</div>
{% else %}

<div>
    <h1 style="text-align: center;">Tizimga kirmagansiz!</h1>
</div>

{% endif %}

{%endblock%}

curriculum/templates/curriculum/lesson_update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Lesson Update {% endblock %}



{% block content %}


{% if user.is_authenticated %}

<div class="site-section ftco-subscribe-1 site-blocks-cover pb-4"
    style="background-image: url('{% static 'images/bg_1.jpg' %}')">
    <div class="container">
        <div class="row align-items-end justify-content-center text-center">
            <div class="col-lg-7">
                <h2 class="mb-0">Darsni yangilash</h2>
                <p>Iltimos ma'lumotlarni aniq qilib yozing</p>
            </div>
        </div>
    </div>
</div>

<div class="custom-breadcrumns border-bottom">
    <div class="container">
        <a href="{% url 'index' %}">Bosh sahifa</a>
        <span class="mx-3 icon-keyboard_arrow_right"></span>
        <a href="{% url 'curriculum:standard_list' %}">Sinflar</a>
        <span class="mx-3 icon-keyboard_arrow_right"></span>
        <span class="current">Darsni yangilash</span>
    </div>
</div>

<div class="site-section justify-content-center">
    <div class="container ">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form|crispy}}
                    <div class="row">
                        <div class="col-md-6" style="margin: 2rem 0;">
                            <input type="submit" value="Yangilash"
                                class="btn btn-warning btn-lg mr-4 btn-block rounded-0">
                        </div>
                        <div class="col-md-6" style="margin: 2rem 0;">
                            <a href="{% url 'curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}"
                                class="btn btn-danger btn-lg mr-4 btn-block rounded-0">Yangilashni bekor qilish</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% else %}

<div>
    <h1 style="text-align: center;">Tizimga kirmagansiz!</h1>
</div>

{% endif %}




{% endblock %}

curriculum/templates/curriculum/standard_list_view.html
{% extends 'base.html' %} {% load static %} {% block title %} Sinflar {% endblock title %} {% block content %}

<div class="site-section ftco-subscribe-1 site-blocks-cover pb-4"
  style="background-image: url('{% static 'images/bg_1.jpg' %}')">
  <div class="container">
    <div class="row align-items-end justify-content-center text-center">
      <div class="col-lg-7">
        <h2 class="mb-0">Guruhlar</h2>
        <p>Barcha guruhlar sahifasi.</p>
      </div>
    </div>
  </div>
</div>

<div class="custom-breadcrumns border-bottom">
  <div class="container">
    <a href="{% url 'index' %}">Bosh sahifa</a>
    <span class="mx-3 icon-keyboard_arrow_right"></span>
    <span class="current">Sinflar</span>
  </div>
</div>

<div class="site-section">
  <div class="container">
    <div class="row mb-5 justify-content-center text-center">
      <div class="col-lg-4 mb-5">
        <h2 class="section-title-underline mb-5">
          <span>O'qishni boshlaymiz</span>
        </h2>
      </div>
    </div>
    <div class="row justify-content-center">
      {% for standard in standards %}
      <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
        <div class="feature-1 border" style="margin-bottom: 2rem">
          <div class="icon-wrapper bg-primary">
            <span class="flaticon-mortarboard text-white"></span>
          </div>
          <div class="feature-1-content">
            <h2>{{standard.name}}</h2>
            <p>Maktabimizning {{standard.name}}lari uchun fanlar to'plami.</p>
            {% if user.is_authenticated %}
            <p>
              <a href="{% url 'curriculum:subject_list' slug=standard.slug %}"
                class="btn btn-primary px-4 rounded-0">O'qishni boshlash</a>
            </p>
            {% else %}
            <p>
              <a href="{% url 'user_login' %}" class="btn btn-primary px-4 rounded-0">O'qishni boshlash</a>
            </p>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock content %}